version: 2
jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      #- image: circleci/python:3.7.2
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/regression_model/requirements.txt
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
            echo 'Decompreser datasets'
            unzip packages/regression_model/regression_model/datasets/*.zip -d packages/regression_model/regression_model/datasets/
            echo 'Contenu du folder datasets'
            ls packages/regression_model/regression_model/datasets
            echo 'Excution des tests'
            py.test -vv packages/regression_model/tests

workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
